# Użyj oficjalnego obrazu Node.js jako bazowego
FROM node:latest

# Ustaw katalog roboczy
WORKDIR /app

# Skopiuj package.json i package-lock.json
COPY package*.json ./

# Zainstaluj zależności
RUN npm install

# Skopiuj resztę aplikacji
COPY . .

# Otwórz port 3000
EXPOSE 3000

# Uruchom serwer Node.js
CMD ["node", "server.js"]
